cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'caskroom/cask'
tap 'caskroom/fonts'

brew 'python'
brew 'node'
brew 'tmux'
brew 'hub'
brew 'diff-so-fancy'
brew 'imagemagick'

cask 'iterm2'
cask '1password'
cask 'google-chrome'
cask 'slack'
cask 'dockertoolbox'
cask 'font-inconsolata'
cask 'visualvm'
