cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'caskroom/cask'
tap 'caskroom/fonts'

brew 'python'
brew 'node'
brew 'tmux'
brew 'hub'
brew 'diff-so-fancy'
brew 'imagemagick'

cask 'java'
cask 'iterm2'
cask 'atom'
cask 'flycut'
cask '1password'
cask 'google-chrome'
cask 'slack'
cask 'dockertoolbox'
cask 'visualvm'

cask 'qlcolorcode'
cask 'qlstephen'
cask 'qlmarkdown'
cask 'quicklook-json'
cask 'qlprettypatch'
cask 'quicklook-csv'
cask 'betterzipql'
cask 'qlimagesize'

cask 'font-inconsolata'
