#!/usr/bin/env bash
#
# bootstrap installs things.

set -e
cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd -P)
source setup/funcs.sh

# set zsh as default
#chsh -s /bin/zsh

echo ''

setup/gitconfig
setup/dotfiles

# If we're on a Mac, let's install and setup homebrew.
if [ "$(uname -s)" == "Darwin" ]
then
  info "installing dependencies"
  if source bin/dot
  then
    success "dependencies installed"
  else
    fail "error installing dependencies"
  fi
fi

echo ''
echo '  All installed!'
