#!/usr/bin/env bash
#
# bootstrap installs things.

set -e
cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd -P)
source setup/funcs.sh

chsh --shell $(which zsh)

echo ''

setup/gitconfig
setup/dotfiles
setup/dependencies

echo ''
echo '  All finished!'
