#!/bin/sh
#
# dot
#
# `dot` handles installation, updates, things like that. Run it periodically
# to make sure you're on the latest and greatest.
export DOTFILES_ROOT=$HOME/.dotfiles

# Set OS X defaults
$DOTFILES_ROOT/osx/set-defaults.sh

# Install homebrew
$DOTFILES_ROOT/homebrew/install.sh 2>&1

# Upgrade homebrew
echo "› brew update"
brew update

# Install software
echo "› $DOTFILES_ROOT/install"
$DOTFILES_ROOT/install
